### ISSUE TITLE
Bug in spearman rho?

### ISSUE THREAD

**Issue by Joe-Hilgard** [MicheleNuijten/statcheck#11]
StatCheck returns p = 1 for a spearman rho test:

https://pubpeer.com/publications/482004022406F33A920A732DC12DCC#fb99015

Apologies if this was fixed in the StatCheck update.

**Comment by MicheleNuijten** [comment]
Nope, not fixed yet! statcheck thinks these rhos are a chi2, I'm still figuring out how to fix the regex. 
If you see anything else weird, please let us know!

Thanks :)

**Comment by MicheleNuijten** [comment]
Fixed now!
