### ISSUE TITLE
Control verbosity

### ISSUE THREAD

**Issue by nico202** [MicheleNuijten/statcheck#26]
It would be nice to have a be able to call `statcheck` with the optional `verbosity = FALSE` parameter that suppresses the following messages:

https://github.com/MicheleNuijten/statcheck/blob/f24a4f9aa128e9c1d28576c45992edca5a264e1c/R/statcheck.R#L56
https://github.com/MicheleNuijten/statcheck/blob/f24a4f9aa128e9c1d28576c45992edca5a264e1c/R/statcheck.R#L57

**Comment by MicheleNuijten** [comment]
Fixed with the argument "messages" in the statcheck function.
