### ISSUE TITLE
Error if there is a space between two numbers after a test statistic and before a decimal in a reported statistical test result

### ISSUE THREAD

**Issue by fsingletonthorn** [MicheleNuijten/statcheck#28]
Errors are caused if there is a space between two numbers after a test statistic and before a decimal in a reported statistical test result. (Scanned several thousand papers and this only occurred once so it's unlikely to pop up too often!)

Examples: 
``` r
statcheck::statcheck(" z = 1 1 .25, p = .806. ")
#> Extracting statistics...
#> 
  |                                                                       
  |                                                                 |   0%
  |                                                                       
  |=================================================================| 100%
#> Error in if (lower[i] < 0) {: missing value where TRUE/FALSE needed
```
``` r
statcheck::statcheck("t(123) = 1 0.25, p = .806")
#> Extracting statistics...
#> 
  |                                                                       
  |                                                                 |   0%
  |                                                                       
  |=================================================================| 100%
#> Error in if (lower[i] < 0) {: missing value where TRUE/FALSE needed
```
<sup>Created on 2019-11-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by MicheleNuijten** [comment]
Thanks for pointing this out! Sorry for the extremely late reply, but I wasn't in the habit of checking GitHub issues (something that will change from now on!). 

I've implemented several updates in the meantime, and this particular bug doesn't seem to occur anymore.

I'll consider that as fixed :)
