### ISSUE TITLE
Displaying χ² for chisq tests

### ISSUE THREAD

**Issue by liebscher** [MicheleNuijten/statcheck#34]
UI/UX could use a quick boost by displaying ASCII characters for parsed Chi-Squared tests. Currently displays something along the lines of "2 (1) = 3.3, p = 0.07" in the output table. Thanks!

**Comment by MicheleNuijten** [comment]
Thanks! I'm forever struggling with the chi2, because R packages don't allow for non-ASCII characters when compiling. But I think I found a way to work around this. Will add to the to-do list :)
