### ISSUE TITLE
Character recognition errors in older PDFs

### ISSUE THREAD

**Issue by ecsalomon** [MicheleNuijten/statcheck#4]
When converting some older PDFs, I've encountered a couple of character recognition errors that I think could be addressed with some updated regex:
- "F(1, X) = Y" gets converted by pdftotext to "F(l, X) = Y"; perhaps include 'l' in regex for F-tests' first degree of freedom (and record as 1)
- "t(X) = Y" gets converted by pdftotext to "r(X) = Y"; perhaps r-tests with Y > 1 get converted to t-tests (and print warning)

**Comment by MicheleNuijten** [comment]
Hi Erika,

Thanks for pointing that out! It actually helped me solving another mysterious bug.
I'm gonna fix the df's in F-tests as you suggest, but I have to think about the problem with the t/r error. Sometimes correlations > 1 are actually reported in papers, and I'd like statcheck to pick that up. I'm thinking about making an option that you can switch on or off that will change correlations >1 into t-tests.

In any case, thanks a lot for pointing this out, I'll try to solve it ASAP!

Best,
Michèle

**Comment by ecsalomon** [comment]
Hi Michèle,

Thanks for your quick response! I see your point about t/r. It happened in
both of the PDFs I tried yesterday, so it may be good to include an
option/warning if there are *r*s over 1. Thanks again!

Cheers,
Erika
