### ISSUE TITLE
Release plan 1.4 and stale develop branch

### ISSUE THREAD

**Issue by J535D165** [MicheleNuijten/statcheck#43]
Thanks for this interesting project. 

I'm wondering what the release plan is for version 1.4. There are prereleases for 1.4 https://github.com/MicheleNuijten/statcheck/releases, but no release yet. 

Another thing I'm wondering about is the stale (?) `develop` branch. What is your plan with this branch? Merge it into master?https://github.com/MicheleNuijten/statcheck/network. There are interesting features in there regarding PDF parsing with pdftools. It might be better to abandon the `develop` branch after merging it into master.

**Comment by MicheleNuijten** [comment]
Hi! Thanks for your message. I've been on sick leave the past year and slowly reintegrating again. This project is high on my list to start working on again :)
