### ISSUE TITLE
allow semicolons instead of commas

### ISSUE THREAD

**Issue by steveharoz** [MicheleNuijten/statcheck#47]
Should there be a comma separating the value and the "p"? Yes. 

Do some authors use a semicolon instead? Also yes.

Look at [final character here](https://github.com/MicheleNuijten/statcheck/blob/a35b5c3c8b3932538b20a6b92043bc1869c29bb9/R/regex.R#L37)

**Comment by MicheleNuijten** [comment]
See https://github.com/MicheleNuijten/statcheck/issues/46#issuecomment-1188728421 :)
