### ISSUE TITLE
optional square brackets for parentheses

### ISSUE THREAD

**Issue by steveharoz** [MicheleNuijten/statcheck#48]
Should authors use parentheses for df? Yes

Do some authors use square brackets instead? Also yes

Change [RGX_OPEN_BRACKET](https://github.com/MicheleNuijten/statcheck/blob/a35b5c3c8b3932538b20a6b92043bc1869c29bb9/R/regex.R#L57) to `"(.+?(?=[\\(\\[]))"`

**Comment by MicheleNuijten** [comment]
See https://github.com/MicheleNuijten/statcheck/issues/46#issuecomment-1188728421 :)
