### ISSUE TITLE
DecisionErrorAlphas boolean absent?

### ISSUE THREAD

**Issue by chartgerink** [MicheleNuijten/statcheck#5]
I get an error that is new to me. I pasted it below. I also attached the text for which I got this. You can read it in to R with `read.table`; I was using `statcheck()` when this error occurred.

ERROR
```
Extracting statistics...
  |=========================================================================| 100%
Error in if (any(DecisionErrorAlphas)) { : 
  missing value where TRUE/FALSE needed
```
[bug_report.txt](https://github.com/MicheleNuijten/statcheck/files/180227/bug_report.txt)

**Comment by MicheleNuijten** [comment]
I solved that bug in the newest version of statcheck on GitHub, it has to do with wrong test statistics (e.g., r>1) that result in computed p-values that are NaN, which make computing a TRUE/FALSE for the DecisionError impossible. It should be solved in the new version, but let me know if it persists!
