### ISSUE TITLE
Correlations incorrectly extracted as Chi2

### ISSUE THREAD

**Issue by chartgerink** [MicheleNuijten/statcheck#8]
Based on the pubpeer reports a bug was found in v1.0.1 where some correlations are incorrectly extracted as Chi2. It is based on [this](http://link.springer.com/article/10.1007%2Fs10802-013-9778-0) paper and the Pubpeer comments are available [here](https://pubpeer.com/publications/7B44613C1F368DA4DDE4498C3D9714).

It might be worthwhile to make these a use case for testing purposes. But definitely something worth looking into. Attached is a `csv` of the results from `statcheck` for this paper.
[issue.txt](https://github.com/MicheleNuijten/statcheck/files/445921/issue.txt)

**Comment by MicheleNuijten** [comment]
This seems to be fixed in the latest CRAN version already :)
