### ISSUE TITLE
Test for validity of confidence intervals?

### ISSUE THREAD

**Issue by LukasWallrich** [MicheleNuijten/statcheck#87]
Greetings from the SIPS conference where we are having an error checking discussion - and all very appreciative of statcheck. Given that confidence intervals are usually produced from standard errors, they can be calculated based on p-value and sample size. Could statcheck add a test of those, given that they have become highly recommended parts of the APA guidelines?

**Comment by MicheleNuijten** [comment]
Sorry (again) for the (very) late reply. I would love to add such a feature, but it has proven extremely difficult to automatically extract sample sizes from (psych) papers. I'm not aware of anyone who has successfully managed this so far..
