### ISSUE TITLE
"test (15)" scraped as "t(15)"

### ISSUE THREAD

**Issue by Joe-Hilgard** [MicheleNuijten/statcheck#9]
I saw something in the statcheck scrape that might be a bug. I think generic tests may get scraped as t-tests. 

For example, in [this paper](http://psycnet.apa.org/journals/psp/50/1/106/), the authors write "Friedman's test (15) = 62.92", and statcheck scrapes it as "t(15) = 62.92". 

I don't know much about Friedman's test (or nonparametric tests in general), but it seems to use its own Q-statistic that is closer to a chi-square distribution.

I don't think this is a common situation, of course, but if the regexp could be tweaked to avoid mistaking "...test (df)" for "t(df)" it would improve the specificity of the statcheck program.

**Comment by SachaEpskamp** [comment]
Interesting problem :) Could try with a negative lookbehind:
```
strings <- c(
  "t(15)","test (15)", "(t(15","test(15)"
)
grep("(?<!\\w)t\\s?\\(", strings, value=TRUE, perl=TRUE)
# [1] "t(15)" "(t(15"
```

**Comment by MicheleNuijten** [comment]
Thanks for pointing that out! That shouldn't happen of course (although I suspect that this doesn't happen that often, luckily). I think the negative lookbehind is a good idea indeed, I'll look into it!
